export ZSH="$HOME/.oh-my-zsh"

date "+%H:%M" | cowsay

ZSH_THEME="powerlevel10k/powerlevel10k"

plugins=(git zsh-autosuggestions zsh-syntax-highlighting)
source $ZSH/oh-my-zsh.sh

alias ..='cd ..'
alias ll='ls -a'
alias home='cd ~'
alias dig='dig +short'
alias ping='ping -c 3'

function apt() {
    case "$1" in
        update|upgrade|autoremove|install)
            nala "$@"
            ;;
        *)
            command apt "$@"
            ;;
    esac
}
