export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="powerlevel10k/powerlevel10k"

plugins=(git zsh-autosuggestions zsh-syntax-highlighting)
source $ZSH/oh-my-zsh.sh

alias ..='cd ..'
alias ...='cd ...'
alias ll='ls -a'
alias home='cd ~'
alias dig='dig +short'
alias ping='ping -c 3'
alias traceroute='mtr'
alias mtr='mtr -t -b'

clear
date "+%H:%M" | cowsay
